server:
  port: 8099
  #配置数据源
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/swqms?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
#      type: com.alibaba.druid.pool.DruidDataSource
#      #连接池配置
#      # 初始化大小，最小等待连接数量，最大等待连接数量，最大连接数
#      initialsize: 1
#      minidle: 1
#      maxidle: 5
#      maxActive: 20
#      #最长等待时间
#      maxWait: 6000
#      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#      timeBetweenEvictionRunsMillis: 60000
#      # 配置一个连接在池中最小生存的时间，单位是毫秒
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: SELECT 1 FROM DUAL
#      testWhileIdle: true
#      testOnBorrow: true
#      testOnReturn: false
#      # 打开PSCache，并且指定每个连接上PSCache的大小
#      poolPreparedStatements: false
#      maxPoolPreparedStatementPerConnectionSize: 20
#      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#      filters: stat,wall,log4j
#      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#      # 合并多个DruidDataSource的监控数据
#      #spring.datasource.useGlobalDataSourceStat=true
#
#
#  #druid监控
#  druid:
#    login:
#      username: root
#      password: root

#mybatis配置
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.swq.pojo
